import type { Metadata } from 'next';
import { Shrikhand, Cabin_Condensed } from 'next/font/google';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import Header from './components/Header';

const shrikhand = Shrikhand({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-shrikhand',
});
const cabin = Cabin_Condensed({
  weight: '500',
  subsets: ['latin'],
  variable: '--font-cabin',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${shrikhand.variable} ${cabin.className} antialiased`}>
        <SessionProvider>
          <Header />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
